version: '3.8'

services:
  # golang
  app:
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: ./build/dockerfiles/app/Dockerfile
    volumes: # マウント
      - ./app:/usr/local/go/src/app
    tty: true # コンテナの永続化
    depends_on:
      - db
    ports:
      - 8080:8080
  # posttgresql
  db:
    build:
      context: .
      dockerfile: ./build/dockerfiles/postgresql/Dockerfile
    environment:
      - POSTGRES_USER=posgre
      - POSTGRES_PASSWORD=password
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./app/database/init:/docker-entrypoint-initdb.d # DBを初期化
    ports:
      - 5432:5432

volumes:
  db-store:
